name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t sleepdeprivedsloth/frontend:latest ./full-stack-app/frontend
          docker push sleepdeprivedsloth/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t sleepdeprivedsloth/backend:latest ./full-stack-app/backend
          docker push sleepdeprivedsloth/backend:latest

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull sleepdeprivedsloth/frontend:latest
            docker pull sleepdeprivedsloth/backend:latest
            docker-compose up -d

